#!/bin/bash

export STUDIO_HOME_DIR=/opt/orchsym/runtime
export STUDIO_CONF_DIR="${STUDIO_HOME_DIR}/conf"
export STUDIO_DATA_DIR="/data/runtime/data"
export STUDIO_LOG_DIR="/data/runtime/log"
export STUDIO_PID_DIR="/var/run/orchsym"

export STUDIO_FLOWCONTROLLER_GRACEFUL_SHUTDOWN_PERIOD='10 sec'

# JVM
export STUDIO_NODE_JVM_MEMORY='1024m'
export STUDIO_JAVA_COMMAND='java'


# Logback logging levels and settings
export STUDIO_LOG_APP_FILE_RETENTION=10
export STUDIO_LOG_USER_FILE_RETENTION=10
export STUDIO_LOG_BOOT_FILE_RETENTION=10


# Web properties
export STUDIO_WEB_HTTP_HOST=${STUDIO_WEB_HTTP_HOST:=$(hostname)}
export STUDIO_WEB_HTTP_PORT=${STUDIO_WEB_HTTP_PORT:=8080}
export STUDIO_WEB_HTTPS_HOST=${STUDIO_WEB_HTTPS_HOST:=$(hostname)}
export STUDIO_WEB_HTTPS_PORT=${STUDIO_WEB_HTTPS_PORT:=8443}
export STUDIO_WEB_MAX_HEADER_SIZE=${STUDIO_WEB_MAX_HEADER_SIZE:='16 KB'}
export STUDIO_WEB_PROXY_CONTEXT_PATH=${STUDIO_WEB_PROXY_CONTEXT_PATH:=''}
export STUDIO_WEB_PROXY_HOST=${STUDIO_WEB_PROXY_HOST:=''}


# NiFi cluster settings
export STUDIO_SINGLE_NODE=${STUDIO_SINGLE_NODE:=true}

# separated by ;
export STUDIO_SERVERS=''
export STUDIO_CLUSTER_NODE_ADDRESS=${STUDIO_CLUSTER_NODE_ADDRESS:=''}
export STUDIO_CLUSTER_NODE_PROTOCOL_PORT=${STUDIO_CLUSTER_NODE_PROTOCOL_PORT:=9092}
# Site to Site properties
export STUDIO_REMOTE_INPUT_HOST=${STUDIO_REMOTE_INPUT_HOST:=''}
export STUDIO_REMOTE_INPUT_SOCKET_PORT=${STUDIO_REMOTE_INPUT_SOCKET_PORT:=9093}


# Logback logging levels and settings
export STUDIO_LOG_APP_FILE_RETENTION=10
export STUDIO_LOG_USER_FILE_RETENTION=10
export STUDIO_LOG_BOOT_FILE_RETENTION=10

export STUDIO_IS_SECURE='false'
export STUDIO_AUTH_TYPE=${STUDIO_AUTH_TYPE:=''}

# Security settings
# These default STUDIO_initial_admin,keystorePasswd,keyPassed,trustsorePasswd string here
# is used together with the default preset keystore.jks,trustore.jks under files directory
# When NIFI is secure, all clients accessing NIFI MUST provide the client certificate and
export STUDIO_CERTS_DIR=${STUDIO_DATA_DIR}/certs
export STUDIO_INITIAL_ADMIN='CN=Runtime, OU=Orchsym'
export STUDIO_CLIENT_CERT_PASSWORD='orchsym'
export STUDIO_SECURITY_KEYSTORE=${STUDIO_CONF_DIR}/keystore.jks
export STUDIO_SECURITY_KEYSTORETYPE=jks
export STUDIO_SECURITY_KEYSTOREPASSWD='orchsym'
export STUDIO_SECURITY_KEYPASSWD="orchsym"
export STUDIO_SECURITY_TRUSTSTORE=${STUDIO_CONF_DIR}/truststore.jks
export STUDIO_SECURITY_TRUSTSTORETYPE=jks
export STUDIO_SECURITY_TRUSTSTOREPASSWD='orchsym'

export STUDIO_NEED_CLIENT_AUTH=${STUDIO_NEED_CLIENT_AUTH:=''}

# Queue swap settings
export STUDIO_QUEUE_SWAP_THRESHOLD=${STUDIO_QUEUE_SWAP_THRESHOLD:=20000}
export STUDIO_SWAP_IN_THREADS=${STUDIO_SWAP_IN_THREADS:=1}
export STUDIO_SWAP_OUT_THREADS=${STUDIO_SWAP_OUT_THREADS:=4}


# Content Repository Settings
export STUDIO_CONTENT_CLAIM_MAX_FLOW_FILES=100
export STUDIO_CONTENT_CLAIM_MAX_APPENDABLE_SIZE='10 MB'
export STUDIO_CONTENT_ARCHIVE_MAX_RETENTION_PERIOD='12 hours'
export STUDIO_CONTENT_ARCHIVE_MAX_USAGE_PERCENTAGE='50%'
export STUDIO_CONTENT_ARCHIVE_ENABLED='false'
export STUDIO_CONTENT_ALWAYS_SYNC='false'

export STUDIO_STUDIO_FLOWCONTROLLER_GRACEFUL_SHUTDOWN_PERIOD=${STUDIO_STUDIO_FLOWCONTROLLER_GRACEFUL_SHUTDOWN_PERIOD:='10 sec'}


# Provenance Settings
export STUDIO_PROVENANCE_IMPLEMENTATION=PersistentProvenanceRepository
export STUDIO_PROVENANCE_MAX_STORAGE_TIME='24 hours'
export STUDIO_PROVENANCE_MAX_STORAGE_SIZE='1 GB'
export STUDIO_PROVENANCE_ROLLOVER_TIME='30 secs'
export STUDIO_PROVENANCE_ROLLOVER_SIZE='100 MB'
export STUDIO_PROVENANCE_QUERY_THREADS=2
export STUDIO_PROVENANCE_INDEX_THREADS=2
export STUDIO_PROVENANCE_REPOSITORY_BUFFER_SIZE=100000
export STUDIO_PROVENANCE_INDEXED_FIELDS='EventType, FlowFileUUID, Filename, ProcessorID, Relationship'


# Status repository settings
export STUDIO_COMPONENTS_STATUS_REPOSITORY_BUFFER_SIZE=1440
export STUDIO_COMPONENTS_STATUS_SNAPSHOT_FREQUENCY='1 min'


# NiFi zookeeper settings
export STUDIO_STATE_MANAGEMENT_EMBEDDED_ZOOKEEPER_START=false
export STUDIO_ZOOKEEPER_SERVERS=''
export STUDIO_ZOOKEEPER_DIR=/data/zookeeper
export STUDIO_ZOOKEEPER_ROOT_NODE='/orchsym'
export STUDIO_ZOOKEEPER_SESSION_TIMEOUT='10 seconds'
export STUDIO_ZOOKEEPER_AUTOPURGE_PURGEINTERVAL=24
export STUDIO_ZOOKEEPER_AUTOPURGE_SNAPRETAINCOUNT=30


export studio_props_file=${STUDIO_CONF_DIR}/orchsym.properties

# 1 - value to search for
# 2 - value to replace
# 3 - file to perform replacement inline
function prop_replace () {
  target_file=${3:-${studio_props_file}}
  sed -i -e "s|^$1=.*$|$1=$2|"  ${target_file}
}

export -f prop_replace
